server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/minhacirurgia?createDatabaseIfNotExist=true
    username: root
    password: root